language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS jpa;'
  - chmod +x gradlew

script: 'SPRING_PROFILES_ACTIVE=dev ./gradlew clean build'

after_success:
  - ./gradlew jacocoTestReport coveralls

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify