language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

services:
  - mysql

before_install:
  - chmod +x gradlew

script: './gradlew clean build -Dspring.profile.active=dev'

after_success:
  - ./gradlew jacocoTestReport coveralls

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify