spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root

  jpa:
    hibernate:
      ddl-auto: create-drop

  devtools:
    livereload:
      enabled: false
    add-properties: false
