spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  devtools:
    livereload:
      enabled: false