spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: validate

  devtools:
    livereload:
      enabled: false