spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa?useSSL=false
    username: root
    data: classpath:data.sql
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  devtools:
    livereload:
      enabled: false
    add-properties: false
